Repository SoftFever/OrcaSlicer, pull requests merged in 2023-11, with the labels that each got.

#2728 Adds overview for custom gcodes like pause, change filament, custom #2191
  src/slic3r/GUI/GCodeViewer.cpp
  src/slic3r/GUI/ImGuiWrapper.cpp
  src/slic3r/GUI/ImGuiWrapper.hpp
Labels: enhancement

#2722 Add option to "Reverse only internal perimeters" under the reverse on odd feature to reduce part warping
  src/libslic3r/PerimeterGenerator.cpp
  src/libslic3r/Preset.cpp
  src/libslic3r/PrintConfig.cpp
  src/libslic3r/PrintConfig.hpp
  src/libslic3r/PrintObject.cpp
  src/slic3r/GUI/ConfigManipulation.cpp
  src/slic3r/GUI/Tab.cpp
Labels: enhancement

#2780 Fix PNG build plate texture not rendering on AMD GPUs
  src/nanosvg/README.txt
  src/nanosvg/nanosvg.h
  src/nanosvg/nanosvgrast.h
  src/slic3r/GUI/GLTexture.cpp
  src/slic3r/GUI/OpenGLManager.cpp
  src/slic3r/GUI/OpenGLManager.hpp
Labels: bug

#2784 Fix toolbar rendering on Windows
  src/slic3r/GUI/GLCanvas3D.cpp
Labels: bug

#2808 Show wireframe in MMU painter gizmo
  resources/shaders/110/mm_gouraud.fs
  resources/shaders/110/mm_gouraud.vs
  resources/shaders/140/mm_gouraud.fs
  resources/shaders/140/mm_gouraud.vs
  resources/shaders/background.fs
  resources/shaders/background.vs
  resources/shaders/flat.fs
  resources/shaders/flat.vs
  resources/shaders/flat_texture.fs
  resources/shaders/flat_texture.vs
  resources/shaders/gouraud.fs
  resources/shaders/gouraud.vs
  resources/shaders/gouraud_130.fs
  resources/shaders/gouraud_130.vs
  resources/shaders/gouraud_light.fs
  resources/shaders/gouraud_light.vs
  resources/shaders/gouraud_light_instanced.fs
  resources/shaders/gouraud_light_instanced.vs
  resources/shaders/mm_contour.fs
  resources/shaders/mm_contour.vs
  resources/shaders/mm_gouraud.fs
  resources/shaders/mm_gouraud.vs
  resources/shaders/mm_gouraud_wireframe.fs
  resources/shaders/mm_gouraud_wireframe.vs
  resources/shaders/outline.fs
  resources/shaders/outline.vs
  resources/shaders/printbed.fs
  resources/shaders/printbed.vs
  resources/shaders/thumbnail.fs
  resources/shaders/thumbnail.vs
  resources/shaders/toolpaths_lines.fs
  resources/shaders/toolpaths_lines.vs
  resources/shaders/variable_layer_height.fs
  resources/shaders/variable_layer_height.vs
  src/slic3r/GUI/GLCanvas3D.cpp
  src/slic3r/GUI/Gizmos/GLGizmoMmuSegmentation.cpp
  src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp
  src/slic3r/GUI/Gizmos/GLGizmoPainterBase.hpp
  src/slic3r/GUI/Plater.cpp
Labels: enhancement

#2704 Some changes to gcode window toggles
  src/slic3r/GUI/GCodeViewer.cpp
  src/slic3r/GUI/GCodeViewer.hpp
  src/slic3r/GUI/GLCanvas3D.cpp
  src/slic3r/GUI/GUI_App.cpp
  src/slic3r/GUI/GUI_App.hpp
  src/slic3r/GUI/MainFrame.cpp
  src/slic3r/GUI/Preferences.cpp
Labels: enhancement

#2716 Various infill improvements
  src/libslic3r/LayerRegion.cpp
  src/libslic3r/PrintConfig.cpp
  src/libslic3r/PrintObject.cpp
  src/slic3r/GUI/ConfigManipulation.cpp
  src/slic3r/GUI/Tab.cpp
Labels: bug, enhancement

#2923 Use windows API to copy files
  src/libslic3r/utils.cpp
Labels: enhancement, QoL
