Repository SoftFever/OrcaSlicer, pull requests merged in 2024-03, with the labels that each got.

#4425 3D Honeycomb - switch direction at smallest bridge point, rather than every layer
  src/libslic3r/Fill/Fill3DHoneycomb.cpp
  src/libslic3r/Fill/Fill3DHoneycomb.hpp
Labels: enhancement

#4416 Inner Outer Inner mode - arachne bug fix
  src/libslic3r/PerimeterGenerator.cpp
Labels: enhancement

#4417 Revised Inner Outer Inner mode for Classic mode
  src/libslic3r/ExtrusionEntity.hpp
  src/libslic3r/PerimeterGenerator.cpp
Labels: enhancement

#4546 Falashforge 5M network support
  src/libslic3r/PrintConfig.cpp
  src/libslic3r/PrintConfig.hpp
  src/slic3r/CMakeLists.txt
  src/slic3r/GUI/PhysicalPrinterDialog.cpp
  src/slic3r/Utils/Flashforge.cpp
  src/slic3r/Utils/Flashforge.hpp
  src/slic3r/Utils/MKS.cpp
  src/slic3r/Utils/PrintHost.cpp
  src/slic3r/Utils/SerialMessage.hpp
  src/slic3r/Utils/SerialMessageType.hpp
  src/slic3r/Utils/TCPConsole.cpp
  src/slic3r/Utils/TCPConsole.hpp
Labels: tester needed

#4734 Fix issue that print host and webui settings are not properly reset
  src/slic3r/GUI/PhysicalPrinterDialog.cpp
Labels: bug
