Repository SoftFever/OrcaSlicer, pull requests merged in 2025-04, with the labels that each got.

#9031 Do not loade web page until switching to device page
  src/slic3r/GUI/PrinterWebView.cpp
  src/slic3r/GUI/PrinterWebView.hpp
Labels: performance

#9019 Fix brim type combox in object table
  src/slic3r/GUI/GUI_ObjectTable.cpp
Labels: bug

#9066 Fix split to objects crash
  src/slic3r/GUI/GUI_ObjectList.cpp
  src/slic3r/GUI/GUI_ObjectList.hpp
Labels: bug

#9114 Make gcode 3mf file smaller when sending to BBL printers
  src/slic3r/GUI/Plater.cpp
Labels: enhancement, QoL

#9115 FIX: prevent dead loop of conflict checker
  src/libslic3r/GCode/ConflictChecker.cpp
Labels: bug

#9145 Ensure the flow calib pattern to be printed in desired order
  src/libslic3r/Fill/FillBase.cpp
  src/libslic3r/Fill/FillPlanePath.cpp
Labels: bug

#9136 Fix shortcut collision on macOS
  src/slic3r/GUI/MainFrame.cpp
Labels: bug, QoL

#8934 Make sure sidebar is not triggered by child notebook tab changes
  src/slic3r/GUI/Plater.cpp
Labels: bug

#8912 Camera rotate around current plate center if plate is empty
  src/slic3r/GUI/GLCanvas3D.cpp
Labels: enhancement, QoL

#9118 Async profile load on printer/filament selection screen
  resources/web/data/text.js
  resources/web/guide/0/index.html
  resources/web/guide/0/load.css
  resources/web/guide/0/load.js
  resources/web/guide/0/loading.svg
  src/slic3r/GUI/WebGuideDialog.cpp
  src/slic3r/GUI/WebGuideDialog.hpp
Labels: enhancement, QoL, performance

#9146 Fix PA calib crash when default line width is set to 0
  src/libslic3r/calib.cpp
  src/libslic3r/calib.hpp
  src/slic3r/GUI/Plater.cpp
Labels: bug

#9167 Fix brim ear paint memory leaking & multi-selection with shift+left click
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.hpp
  src/slic3r/GUI/ImGuiWrapper.cpp
Labels: bug, QoL, performance

#9150 Fix issue that option visibility not updated after resetting
  src/slic3r/GUI/Tab.cpp
Labels: bug

#9174 Improve brim paint gizmo shortcuts
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.hpp
  src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
Labels: enhancement, QoL

#8776 Don't allow selection change in paint gizmo
  src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp
Labels: bug, QoL, 2.3.1

#9149 Don't apply adaptive PA in PA calibration
  src/libslic3r/GCode.cpp
Labels: bug

#9179 Fix wrong travel before printing first skirt point
  src/libslic3r/GCode.cpp
  src/libslic3r/GCode.hpp
Labels: bug

#9189 Fix flow calibration overlapping objects with nozzle > 0.4mm
  src/slic3r/GUI/Plater.cpp
Labels: bug

#9197 Avoid unnecessary travel in scarf seam
  src/libslic3r/GCode.cpp
Labels: bug

#9202 Fix `M486` still presented even with obj exclusion disabled
  src/libslic3r/GCode.cpp
Labels: bug

#9222 Fix wipe tower initial movement when switching extruder offsets
  src/libslic3r/GCode.cpp
Labels: bug

#9260 Fix orca filament lib load
  src/slic3r/GUI/WebGuideDialog.cpp
Labels: bug

#8767 Fix grid lines not aligned to origin
  src/slic3r/GUI/PartPlate.cpp
Labels: 2.3.1

#9333 Fix: Circular bed shape (without 3D model) not rendering in correct position
  src/slic3r/GUI/3DBed.cpp
Labels: bug

#8869 Attempt to speed up outside bed detection
  src/libslic3r/BoundingBox.hpp
  src/libslic3r/BuildVolume.cpp
  src/libslic3r/Model.cpp
  src/slic3r/GUI/Plater.cpp
Labels: enhancement, performance

#9126 Fix AMS filament selection compatible check
  src/slic3r/GUI/AMSMaterialsSetting.cpp
Labels: bug

#9371 Fix selected filament not shown up
  resources/profiles/Flashforge/filament/Generic ASA @Flashforge AD4.json
  resources/profiles/Flashforge/filament/Generic PLA Silk @Flashforge AD4.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU PETG @FF AD5M 0.25 nozzle.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU PETG @FF AD5M 0.8 nozzle.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU PLA Marble @base.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU PLA Matte @FF AD5M 0.25 nozzle.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU PLA+ 2.0 @FF AD5M 0.25 nozzle.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU PLA+ @FF AD5M 0.25 nozzle.json
  resources/profiles/Flashforge/filament/SUNLU/SUNLU Silk PLA+ @FF AD5M 0.25 nozzle.json
  resources/profiles/Z-Bolt/filament/Z-Bolt ABS HT @0.4 nozzle.json
  scripts/orca_extra_profile_check.py
Labels: bug

#9389 Improve profile check script
  scripts/orca_extra_profile_check.py
Labels: bug, enhancement, QoL

#7405 Fix #6839 with final tool preheating on multitool machines causing in…
  src/libslic3r/GCode/GCodeProcessor.cpp
Labels: bug, ToolChanger

#9332 Merge tiny cracks that is part of a large bottom surface into bottom surface
  src/libslic3r/PrintObject.cpp
Labels: bug
