Repository SoftFever/OrcaSlicer, pull requests merged in 2025-05, with the labels that each got.

#9473 Fix object search bar on macOS and Linux
  src/slic3r/GUI/Plater.cpp
  src/slic3r/GUI/Search.cpp
  src/slic3r/GUI/Search.hpp
Labels: bug, upstream bug, QoL

#9422 Fix Xcode 16.3 build
  deps/CGAL/0001-clang19.patch
  deps/CGAL/CGAL.cmake
  deps/OpenCV/0002-clang19-macos.patch
  deps/OpenCV/OpenCV.cmake
  deps/OpenVDB/0001-clang19.patch
  deps/OpenVDB/OpenVDB.cmake
  deps/PNG/0002-clang19-macos.patch
  deps/PNG/PNG.cmake
  src/slic3r/GUI/GUI_App.cpp
  src/slic3r/GUI/ModelMall.cpp
  src/slic3r/GUI/Project.cpp
  src/slic3r/GUI/WebDownPluginDlg.cpp
  src/slic3r/GUI/WebGuideDialog.cpp
Labels: bug

#9344 Fix vendor/model selector on create printer dialog
  scripts/generate_presets_vendors.py
  src/slic3r/GUI/CreatePresetsDialog.cpp
Labels: bug

#9358 PA calib: Don't decrease speed too much for the speed trick line
  src/libslic3r/calib.cpp
Labels: bug

#9363 Show proper printer names on printer selection page
  resources/web/guide/21/21.js
  resources/web/guide/24/24.js
  src/slic3r/GUI/WebGuideDialog.cpp
Labels: bug, QoL

#9393 Fix floating brim
  src/libslic3r/GCode.cpp
Labels: bug

#9584 Fix crash when `start_extruder_id` is empty
  src/libslic3r/GCode/ToolOrdering.cpp
Labels: bug

#9417 Fix crash when switching back to prepare tab after clicking the support paint icon in preview
  src/slic3r/GUI/Plater.cpp
Labels: bug

#9405 Make Custom GCode Editor resizable
  src/slic3r/GUI/EditGCodeDialog.cpp
  src/slic3r/GUI/GUI_Utils.cpp
  src/slic3r/GUI/GUI_Utils.hpp
Labels: enhancement, QoL

#9605 Fix brim ear render when camera projection changed
  src/slic3r/GUI/3DBed.cpp
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
Labels: bug

#9604 Gizmo shortcuts
  localization/i18n/OrcaSlicer.pot
  localization/i18n/ca/OrcaSlicer_ca.po
  localization/i18n/cs/OrcaSlicer_cs.po
  localization/i18n/de/OrcaSlicer_de.po
  localization/i18n/en/OrcaSlicer_en.po
  localization/i18n/es/OrcaSlicer_es.po
  localization/i18n/fr/OrcaSlicer_fr.po
  localization/i18n/hu/OrcaSlicer_hu.po
  localization/i18n/it/OrcaSlicer_it.po
  localization/i18n/ja/OrcaSlicer_ja.po
  localization/i18n/ko/OrcaSlicer_ko.po
  localization/i18n/lt/OrcaSlicer_lt.po
  localization/i18n/nl/OrcaSlicer_nl.po
  localization/i18n/pl/OrcaSlicer_pl.po
  localization/i18n/pt_BR/OrcaSlicer_pt_BR.po
  localization/i18n/ru/OrcaSlicer_ru.po
  localization/i18n/sv/OrcaSlicer_sv.po
  localization/i18n/tr/OrcaSlicer_tr.po
  localization/i18n/uk/OrcaSlicer_uk.po
  localization/i18n/zh_CN/OrcaSlicer_zh_CN.po
  localization/i18n/zh_TW/OrcaSlicer_zh_TW.po
  src/slic3r/GUI/ConfigManipulation.cpp
  src/slic3r/GUI/Gizmos/GLGizmoAssembly.cpp
  src/slic3r/GUI/Gizmos/GLGizmoAssembly.hpp
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
  src/slic3r/GUI/KBShortcutsDialog.cpp
Labels: bug, enhancement, QoL

#9600 Fix new project crash on Windows if multi-extruder printer profile is edited
  src/slic3r/GUI/Tab.cpp
  src/slic3r/GUI/Tab.hpp
Labels: bug

#9529 Fix preview gcode misalignment caused by placeholder postprocess
  src/libslic3r/GCode/GCodeProcessor.cpp
Labels: bug

#9625 Brim ear updates model object in real-time
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.cpp
  src/slic3r/GUI/Gizmos/GLGizmoBrimEars.hpp
  src/slic3r/GUI/Gizmos/GLGizmosManager.cpp
Labels: bug

#9574 Make sure `filament_id` is not longer than 8 chars if the filament can be set in AMS
  resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-CF @base.json
  resources/profiles/OrcaFilamentLibrary/filament/AliZ/AliZ PETG-Metal @base.json
  resources/profiles/OrcaFilamentLibrary/filament/base/fdm_filament_sbs.json
  scripts/orca_extra_profile_check.py
Labels: bug
