Repository SoftFever/OrcaSlicer, pull requests merged in 2025-06, with the labels that each got.

#9821 Fix error when drag-n-drop a file from network location to home screen
  src/slic3r/GUI/WebViewDialog.cpp
Labels: bug

#9825 Remove sensitive data in 3mf files
  src/libslic3r/Format/3mf.cpp
  src/libslic3r/Format/bbs_3mf.cpp
Labels: enhancement

#7177 Upgrade clipper & improve multi-thread performance
  src/CMakeLists.txt
  src/clipper/CMakeLists.txt
  src/clipper/clipper.cpp
  src/clipper/clipper.hpp
  src/clipper2/CMakeLists.txt
  src/clipper2/Clipper2Lib/include/clipper2/clipper.core.h
  src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h
  src/clipper2/Clipper2Lib/include/clipper2/clipper.export.h
  src/clipper2/Clipper2Lib/include/clipper2/clipper.h
  src/clipper2/Clipper2Lib/include/clipper2/clipper.minkowski.h
  src/clipper2/Clipper2Lib/include/clipper2/clipper.offset.h
  src/clipper2/Clipper2Lib/include/clipper2/clipper.rectclip.h
  src/clipper2/Clipper2Lib/src/clipper.engine.cpp
  src/clipper2/Clipper2Lib/src/clipper.offset.cpp
  src/clipper2/Clipper2Lib/src/clipper.rectclip.cpp
  src/libslic3r/Algorithm/LineSplit.hpp
  src/libslic3r/Arachne/WallToolPaths.cpp
  src/libslic3r/BoundingBox.cpp
  src/libslic3r/BoundingBox.hpp
  src/libslic3r/CMakeLists.txt
  src/libslic3r/Clipper2Utils.cpp
  src/libslic3r/Clipper2Utils.hpp
  src/libslic3r/ClipperUtils.cpp
  src/libslic3r/ClipperUtils.hpp
  src/libslic3r/EdgeGrid.hpp
  src/libslic3r/ExPolygon.cpp
  src/libslic3r/GCode.cpp
  src/libslic3r/Geometry.hpp
  src/libslic3r/JumpPointSearch.cpp
  src/libslic3r/MultiPoint.cpp
  src/libslic3r/MultiPoint.hpp
  src/libslic3r/PerimeterGenerator.cpp
  src/libslic3r/Point.hpp
  src/libslic3r/Polygon.cpp
  src/libslic3r/Polygon.hpp
  src/libslic3r/PolygonTrimmer.hpp
  src/libslic3r/Print.cpp
  src/libslic3r/Print.hpp
  src/libslic3r/PrintObject.cpp
  src/libslic3r/SLA/ConcaveHull.cpp
  src/libslic3r/SLA/Pad.hpp
  src/libslic3r/SLA/SupportTree.hpp
  src/libslic3r/ShortestPath.hpp
  src/libslic3r/Support/SupportMaterial.cpp
  src/libslic3r/libslic3r.h
  src/slic3r/GUI/GLModel.hpp
Labels: enhancement, performance

#9548 Ironing support interfaces
  src/libslic3r/GCode.cpp
  src/libslic3r/GCode.hpp
  src/libslic3r/Preset.cpp
  src/libslic3r/PrintConfig.cpp
  src/libslic3r/PrintConfig.hpp
  src/libslic3r/PrintObject.cpp
  src/libslic3r/Support/SupportCommon.cpp
  src/libslic3r/Support/SupportParameters.hpp
  src/slic3r/GUI/ConfigManipulation.cpp
  src/slic3r/GUI/Tab.cpp
Labels: enhancement

#9932 Remove usage of titlebar icons
  src/slic3r/GUI/AboutDialog.cpp
  src/slic3r/GUI/AmsMappingPopup.cpp
  src/slic3r/GUI/BindDialog.cpp
  src/slic3r/GUI/Calibration.cpp
  src/slic3r/GUI/CreatePresetsDialog.cpp
  src/slic3r/GUI/DownloadProgressDialog.cpp
  src/slic3r/GUI/GUI_ObjectTable.cpp
  src/slic3r/GUI/KBShortcutsDialog.cpp
  src/slic3r/GUI/ModelMall.cpp
  src/slic3r/GUI/MsgDialog.cpp
  src/slic3r/GUI/MultiMachinePage.cpp
  src/slic3r/GUI/ObjColorDialog.cpp
  src/slic3r/GUI/ParamsPanel.cpp
  src/slic3r/GUI/PlateSettingsDialog.cpp
  src/slic3r/GUI/Preferences.cpp
  src/slic3r/GUI/PrintOptionsDialog.cpp
  src/slic3r/GUI/PrivacyUpdateDialog.cpp
  src/slic3r/GUI/PublishDialog.cpp
  src/slic3r/GUI/RecenterDialog.cpp
  src/slic3r/GUI/ReleaseNote.cpp
  src/slic3r/GUI/SavePresetDialog.cpp
  src/slic3r/GUI/SelectMachine.cpp
  src/slic3r/GUI/SendMultiMachinePage.cpp
  src/slic3r/GUI/SendToPrinter.cpp
  src/slic3r/GUI/StatusPanel.cpp
  src/slic3r/GUI/StepMeshDialog.cpp
  src/slic3r/GUI/UnsavedChangesDialog.cpp
  src/slic3r/GUI/UpdateDialogs.cpp
  src/slic3r/GUI/WebUserLoginDialog.cpp
  src/slic3r/GUI/WipeTowerDialog.cpp
Labels: UI/UX

#9964 Link libspnav statically
  CMakeLists.txt
  src/slic3r/CMakeLists.txt
Labels: bug

#9983 Fix invalid value for `symmetric_infill_y_axis`
  resources/profiles/BBL/process/fdm_process_common.json
Labels: bug

#9982 Fix notification position on scaling
  src/slic3r/GUI/NotificationManager.cpp
Labels: enhancement, UI/UX

#9432 Infill Line Multiplier
  src/libslic3r/Fill/Fill.cpp
  src/libslic3r/Fill/Fill3DHoneycomb.cpp
  src/libslic3r/Fill/FillAdaptive.cpp
  src/libslic3r/Fill/FillBase.cpp
  src/libslic3r/Fill/FillBase.hpp
  src/libslic3r/Fill/FillCrossHatch.cpp
  src/libslic3r/Fill/FillGyroid.cpp
  src/libslic3r/Fill/FillHoneycomb.cpp
  src/libslic3r/Fill/FillLightning.cpp
  src/libslic3r/Fill/FillRectilinear.cpp
  src/libslic3r/Fill/FillTpmsD.cpp
  src/libslic3r/Preset.cpp
  src/libslic3r/PrintConfig.cpp
  src/libslic3r/PrintConfig.hpp
  src/libslic3r/PrintObject.cpp
  src/slic3r/GUI/ConfigManipulation.cpp
  src/slic3r/GUI/Tab.cpp
Labels: 2.3.1
