Repository SoftFever/OrcaSlicer, pull requests merged in 2025-03, with the labels that each got.

#7199 pa calib: batch mode for pa pattern
  doc/Calibration.md
  doc/adaptive-pressure-advance.md
  doc/images/pa/pa-pattern-batch-objects.png
  doc/images/pa/pa-pattern-batch-plater.png
  doc/images/pa/pa-pattern-batch.png
  doc/images/pa/pa-pattern-single.png
  src/libslic3r/calib.cpp
  src/libslic3r/calib.hpp
  src/slic3r/GUI/Plater.cpp
  src/slic3r/GUI/Plater.hpp
  src/slic3r/GUI/calib_dlg.cpp
  src/slic3r/GUI/calib_dlg.hpp
  src/slic3r/Utils/CalibUtils.cpp
Labels: 2.3.0

#8648 Add SV06 high-speed settings which were incomplete earlier
  resources/profiles/Sovol.json
  resources/profiles/Sovol/filament/Sovol Generic ABS.json
  resources/profiles/Sovol/filament/Sovol Generic PETG.json
  resources/profiles/Sovol/filament/Sovol Generic PLA.json
  resources/profiles/Sovol/filament/Sovol Generic TPU.json
  resources/profiles/Sovol/machine/Sovol SV06 0.4 High-Speed nozzle.json
  resources/profiles/Sovol/machine/Sovol SV06.json
  resources/profiles/Sovol/process/0.20mm High-Speed @Sovol SV06.json
Labels: wait for response

#8993 Improve flow rate calibration: use ipArchimedeanChords pattern for flow rate calibration
  src/libslic3r/Fill/FillBase.cpp
  src/libslic3r/Preset.cpp
  src/libslic3r/PrintConfig.cpp
  src/libslic3r/PrintConfig.hpp
  src/slic3r/GUI/Plater.cpp
Labels: enhancement, Community testers wanted, 2.3.1

#8456 Only consider part above plate when checking for object outside
  src/libslic3r/Model.cpp
  src/libslic3r/Model.hpp
  src/slic3r/GUI/3DScene.cpp
  src/slic3r/GUI/PartPlate.cpp
Labels: 2.3.1

#8198 gCode Legend & Viewer Improvements
  resources/images/im_code.svg
  resources/images/im_fold.svg
  resources/images/im_hidden.svg
  resources/images/im_unfold.svg
  resources/images/im_visible.svg
  src/imgui/imconfig.h
  src/slic3r/GUI/GCodeViewer.cpp
  src/slic3r/GUI/GCodeViewer.hpp
  src/slic3r/GUI/ImGuiWrapper.cpp
Labels: 2.3.1
